# SPDX-License-Identifier: Apache-2.0
"""IOCTL construction and execution for KFD."""

from __future__ import annotations

import ctypes
import fcntl
import functools
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Type

# Direction constants for ioctl
_IOC_WRITE = 1
_IOC_READ = 2

# KFD ioctl type character
_IOC_TYPE = ord("K")

# Pre-compiled regex for parsing ioctl definitions from autogen
_IOCTL_PATTERN = re.compile(
    r"# (AMDKFD_IOC_[A-Z0-9_]+) = (_IOWR?)\('K',\s*nr,\s*type\) "
    r"\(\s*(0x[0-9a-fA-F]+)\s*,\s*struct\s+([A-Za-z0-9_]+)\s*\) # macro"
)

_DIRECTION_MAP = {
    "_IOW": _IOC_WRITE,
    "_IOR": _IOC_READ,
    "_IOWR": _IOC_WRITE | _IOC_READ,
}


@dataclass(frozen=True)
class IoctlDef:
    """Definition of a single ioctl command."""

    name: str
    direction: int  # 1=write, 2=read, 3=read+write
    number: int
    struct_type: Type[ctypes.Structure]

    @property
    def cmd(self) -> int:
        """Compute the ioctl command number."""
        size = ctypes.sizeof(self.struct_type)
        return (self.direction << 30) | (size << 16) | (_IOC_TYPE << 8) | self.number

    @property
    def struct_size(self) -> int:
        """Size of the struct in bytes."""
        return ctypes.sizeof(self.struct_type)


def execute_ioctl(
    fd: int,
    ioctl_def: IoctlDef,
    **kwargs: Any,
) -> ctypes.Structure:
    """
    Execute an ioctl command.

    Args:
        fd: File descriptor
        ioctl_def: IOCTL definition
        **kwargs: Arguments to initialize the struct

    Returns:
        The filled structure after ioctl call

    Raises:
        RuntimeError: If ioctl fails
    """
    struct = ioctl_def.struct_type(**kwargs)
    try:
        fcntl.ioctl(fd, ioctl_def.cmd, struct)
    except OSError as e:
        raise RuntimeError(
            f"IOCTL {ioctl_def.name} failed: {os.strerror(e.errno)}"
        ) from e
    return struct


def execute_ioctl_raw(
    fd: int,
    ioctl_def: IoctlDef,
    data: bytes,
) -> bytes:
    """
    Execute an ioctl with raw bytes (for fuzzing).

    Args:
        fd: File descriptor
        ioctl_def: IOCTL definition
        data: Raw bytes to pass as struct

    Returns:
        Modified bytes after ioctl call

    Raises:
        RuntimeError: If ioctl fails
    """
    expected_size = ioctl_def.struct_size

    # Create mutable buffer of correct size
    if len(data) == expected_size:
        buf = bytearray(data)
    elif len(data) < expected_size:
        buf = bytearray(data) + bytearray(expected_size - len(data))
    else:
        buf = bytearray(data[:expected_size])

    try:
        fcntl.ioctl(fd, ioctl_def.cmd, buf)
    except OSError as e:
        raise RuntimeError(
            f"IOCTL {ioctl_def.name} failed: {os.strerror(e.errno)}"
        ) from e
    return bytes(buf)


class IoctlCollection:
    """
    Collection of KFD ioctl commands as callable methods.

    Each ioctl becomes a method: collection.alloc_memory_of_gpu(fd, **kwargs)
    """

    def __init__(self, ioctls: dict[str, IoctlDef], source_path: Path | None = None):
        self._ioctls = ioctls
        self._source_path = source_path
        # Create bound methods for each ioctl
        for name, ioctl_def in ioctls.items():
            setattr(self, name, functools.partial(execute_ioctl, ioctl_def=ioctl_def))

    def get_definition(self, name: str) -> IoctlDef | None:
        """Get ioctl definition by name."""
        return self._ioctls.get(name)

    def list_ioctls(self) -> list[str]:
        """List all available ioctl names."""
        return list(self._ioctls.keys())

    def __len__(self) -> int:
        return len(self._ioctls)

    def __contains__(self, name: str) -> bool:
        return name in self._ioctls

    def __repr__(self) -> str:
        return f"IoctlCollection({len(self._ioctls)} ioctls)"


# Module-level cache
_cached_ioctls: IoctlCollection | None = None
_cached_source_mtime: float = 0.0


def get_ioctls(force_reload: bool = False) -> IoctlCollection:
    """
    Get the collection of KFD ioctls.

    Parses autogenerated kfd.py on first call, caches result.
    Automatically reloads if source file has been modified.

    Args:
        force_reload: Force reparsing even if cached

    Returns:
        IoctlCollection with all available ioctls

    Raises:
        ImportError: If autogen module not found
    """
    global _cached_ioctls, _cached_source_mtime

    import fuzzyHSA.kfd.autogen.kfd as kfd_module

    source_path = Path(kfd_module.__file__)

    # Check if we need to reload
    if not force_reload and _cached_ioctls is not None:
        try:
            current_mtime = source_path.stat().st_mtime
            if current_mtime == _cached_source_mtime:
                return _cached_ioctls
        except OSError:
            pass

    # Parse and cache
    _cached_ioctls = _parse_ioctls_from_module(kfd_module, source_path)
    try:
        _cached_source_mtime = source_path.stat().st_mtime
    except OSError:
        _cached_source_mtime = 0.0

    return _cached_ioctls


def clear_ioctl_cache() -> None:
    """Clear the cached ioctl collection."""
    global _cached_ioctls, _cached_source_mtime
    _cached_ioctls = None
    _cached_source_mtime = 0.0


def _parse_ioctls_from_module(kfd_module: Any, source_path: Path) -> IoctlCollection:
    """
    Parse ioctl definitions from autogenerated kfd module.

    The autogen creates comments like:
    # AMDKFD_IOC_ALLOC_MEMORY_OF_GPU = _IOWR('K', nr, type) (0x18, struct kfd_ioctl_alloc_memory_of_gpu_args) # macro
    """
    source = source_path.read_text()
    ioctls: dict[str, IoctlDef] = {}

    for match in _IOCTL_PATTERN.finditer(source):
        full_name, direction_str, number_hex, struct_name = match.groups()
        # Convert AMDKFD_IOC_ALLOC_MEMORY_OF_GPU -> alloc_memory_of_gpu
        name = full_name.replace("AMDKFD_IOC_", "").lower()
        struct_type = getattr(kfd_module, f"struct_{struct_name}", None)

        if struct_type is None:
            continue

        ioctls[name] = IoctlDef(
            name=name,
            direction=_DIRECTION_MAP[direction_str],
            number=int(number_hex, 16),
            struct_type=struct_type,
        )

    return IoctlCollection(ioctls, source_path)


def struct_to_bytes(struct: ctypes.Structure) -> bytes:
    """Convert a ctypes Structure to bytes."""
    return bytes(struct)


def bytes_to_struct(data: bytes, struct_type: Type[ctypes.Structure]) -> ctypes.Structure:
    """Convert bytes to a ctypes Structure."""
    return struct_type.from_buffer_copy(data)
